version: '2'

services:
  alpha_ess_2_mqtt:
    container_name: alphaEss2Mqtt
    restart: always
    build:
      context: .
    image: alpha_ess_2_mqtt
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      MQTT.HOST: host
      MQTT.PASSWORD: password
      #      MQTT.DISCOVERY_TOPIC: test
      #      MQTT.PROTOCOLL: mqtt
      MQTT.USERNAME: username
      MQTT.PORT: port
      ALPHA.USERNAME: user
      ALPHA.PASSWORD: p@ssword
