version: '2'
services:
  alpha_ess_gateway:
    build: .
    image: alpha_ess_gateway
    working_dir: /app
    ports:
      - "8007:8080"
    # Substitute the following with whatever
    # makes sense for your java webapp
    command: mvn jetty:run