development.driver=org.mariadb.jdbc.Driver
development.username=kettle
development.password=ONMW2yYgTJOVopWKnPKj
development.url=jdbc:mysql://192.168.11.50:3308/kettle

test.driver=org.mariadb.jdbc.Driver
test.username=kettle
test.password=ONMW2yYgTJOVopWKnPKj
test.url=jdbc:mysql://192.168.11.50:3308/kettle

production.driver=org.mariadb.jdbc.Driver
production.username=kettle
production.password=ONMW2yYgTJOVopWKnPKj
production.url=jdbc:mysql://192.168.11.50:3308/kettle