development.driver=org.mariadb.jdbc.Driver
development.username=
development.password=
development.url=
test.driver=org.mariadb.jdbc.Driver
test.username=
test.password=
test.url=
production.driver=org.mariadb.jdbc.Driver
production.username=
production.password=
production.url=