package de.vdw.io.alpha2mqtt.models.api.charge;

import java.util.List;
import de.vdw.io.alpha2mqtt.models.api.ChargingPileDto;
import lombok.Data;

@Data
public class SettingDto {
  int ac_tied;
  int auto_soccalib_en;
  int auto_startdg_en = 0;
  int backupbox;
  String bakbox_ver;
  int basic_mode_jp;
  String bat_high_cap;
  int bat_highcap_we;
  String bat_use_cap;
  int bat_usecap_we;
  String channel1;
  String channel2;
  int charge_mode1;
  int charge_mode2;
  String charge_soc1;
  String charge_soc2;
  String charge_weekend;
  String charge_workdays;
  List<ChargingPileDto> charging_pile_list;
  int chargingmode;
  int chargingpile;
  String chargingpile_id;
  String chargingpile_sn;
  int chargingpile_switch;
  String control_mode1;
  String control_mode2;
  int ctr_dis;
  int ctr_dis_we;
  int currentsetting;
  String date1;
  String date2;
  int delay1;
  int delay2;
  int delta;
  int dg_cap;
  int dg_frequency;
  int duration1;
  int duration2;
  String ems_version;
  String end_time1a;
  String end_time1b;
  String end_time2a;
  String end_time2b;
  String fill_e1a;
  String fill_e2a;
  String fill_s1a;
  String fill_s2a;
  int fillvalue;
  int gc_charge_power;
  int gc_output_mode;
  int gc_rate_percent;
  int gc_rated_power;
  int gc_soc_end;
  int gc_soc_start;
  String gc_time_end;
  String gc_time_start;
  int generator;
  int generator_mode;
  int grid_charge;
  int grid_Charge_we;
  int l1_priority;
  String l1_soc_limit;
  int l2_priority;
  String l2_soc_limit;
  int l3_priority;
  String l3_soc_limit;
  String languageCode = "de-DE";
  int loadcut_soc;
  int loadtied_soc;
  int max_gridcharge = 10;
  String mbat;
  String minv;
  int pause1;
  int pause2;
  int peace_mode_jp;
  String peak_e1a;
  String peak_e2a;
  int peak_fill_en;
  String peak_s1a;
  String peak_s2a;
  int peakvalue;
  int pm_max;
  int pm_offset;
  String pm_offset_e1a;
  String pm_offset_e2a;
  int pm_offset_en;
  String pm_offset_s1a;
  String pm_offset_s2a;
  int priority;
  int soc_50_flag;
  String start_time1a;
  String start_time1b;
  String start_time2a;
  String start_time2b;
  int stoinv_type;
  int sts_en = 1;
  int switch_off1;
  int switch_off2;
  int switch_on1;
  int switch_on2;
  String sys_sn;
  String system_id;
  String time_cha_ewe1a;
  String time_cha_ewe2a;
  String time_cha_fwe1a;
  String time_cha_fwe2a;
  String time_chae1a;
  String time_chae2a;
  String time_chaf1a;
  String time_chaf2a;
  int time_charge_1;
  int time_charge_2;
  String time_charge_e1;
  String time_charge_e2;
  String time_charge_s1;
  String time_charge_s2;
  String time_dis_ewe1a;
  String time_dis_ewe2a;
  String time_dis_fwe1a;
  String time_dis_fwe2a;
  String time_dise1a;
  String time_dise2a;
  String time_disf1a;
  String time_disf2a;
  String ups1;
  String ups2;
  int upsReserve;
  int vpp_mode_jp;

  public void setWallbox(ChargingPileDto chargingPileDto) {
    chargingpile_id = chargingPileDto.getChargingpile_id();
    chargingpile_sn = chargingPileDto.getChargingpile_sn();
    time_charge_1 = chargingPileDto.getTime_charge_1();
    time_charge_2 = chargingPileDto.getTime_charge_2();
    time_charge_s1 = chargingPileDto.getTime_charge_s1();
    time_charge_e1 = chargingPileDto.getTime_charge_e1();
    time_charge_s2 = chargingPileDto.getTime_charge_s2();
    time_charge_e2 = chargingPileDto.getTime_charge_e2();
    chargingpile_switch = chargingPileDto.getChargingpile_switch();
    priority = chargingPileDto.getPriority();
  }
}
